# Generated by Django 5.1.5 on 2025-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
