# Generated by Django 5.1.5 on 2025-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
