# Generated by Django 5.1.5 on 2025-01-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_album_cover_art_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_id',
            field=models.CharField(max_length=255),
        ),
    ]
