# Generated by Django 5.1.5 on 2025-01-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_review_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.CharField(choices=[('album', 'Album'), ('track', 'Track'), ('artist', 'Artist')], max_length=10),
        ),
    ]
