# Generated by Django 5.1.5 on 2025-01-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recentsearch_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_id',
            field=models.PositiveIntegerField(),
        ),
    ]
