# Generated by Django 5.1.5 on 2025-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_review_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
